order/urls.py
from django.conf.urls import url, include
from order import views
# from .views import AddProductView


urlpatterns = [
    url(
        r'^create_order/(?P<product_pk>\d+)/$',
        views.ChoseOrderType,
        name='chose_order_type'
    ),
    url(
        r'^create_order/(?P<product_pk>\d+)/(?P<order_type_pk>\d+)/$',
        views.OrderCreate,
        name='order_create'
    ),
    url(r'^error_pay/$', views.ErrorPay.as_view(), name='error_pay'),
    url(r'^done_pay/$', views.DonePay.as_view(), name='done_pay'),
]

products/urls.py
from django.conf.urls import url, include
from products import views
# from .views import AddProductView
from products.views import SearchProductView, chart_period

urlpatterns = [
    url(r'^search/$', SearchProductView.as_view(), name='product_search'),
    url(
        r'^$',
        views.ProductListView.as_view(),
        name='products'
    ),
    url(
        r'^product_detail/(?P<pk>\d+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'add/$',
        views.add_product,
        name='add',
    ),
    url(
        r'get_parameters/$',
        views.get_parameters,
        name='get_parameters',
    ),
    url(r'period-chart/(?P<period>\d+)/(?P<pk>\d+)/$', chart_period, name='chart_period')
]

sellfone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles import views

from products.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', index, name='index'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^price_wizard/', include('price_wizard.urls', namespace='price_wizard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

users/urls.py
from django.conf.urls import url, include
from users import views


urlpatterns = [
    url(
        r'^$',
        views.Cabinet.as_view(),
        name='cabinet'
    ),
    url(
        r'^update/$',
        views.ProfileUpdateView.as_view(),
        name='update'
    ),
    url(
        r'^rating/$',
        views.ProfileRatingView.as_view(),
        name='rating'
    ),
    url(
        r'^purchases/$',
        views.ProfilePurchasesView.as_view(),
        name='purchases'
    ),
    url(
        r'^sales/$',
        views.ProfileSalesView.as_view(),
        name='sales'
    ),
    url(
        r'^settings/$',
        views.ProfileSettingsView.as_view(),
        name='settings'
    ),
]

users/models.py
# coding=utf-8
# -*- coding; utf-8 -*-
from __future__ import unicode_literals

import os
import urllib

from allauth.account.signals import user_signed_up
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.files import File
from django.core.validators import RegexValidator
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext as _

from world.models import Territory


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, phone, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, phone=None, password=None,
                    **extra_fields):
        for field in ('is_staff', 'is_superuser'):
            extra_fields.setdefault(field, False)
        return self._create_user(email, phone, password, **extra_fields)

    def create_superuser(self, email, phone, password, **extra_fields):
        for field in ('is_staff', 'is_superuser'):
            if extra_fields.setdefault(field, True) is not True:
                raise ValueError('Superuser must have %s=True' % field)
        return self._create_user(email, phone, password, **extra_fields)


class User(AbstractUser):
    objects = UserManager()

    username_validator = UnicodeUsernameValidator()

    first_name = models.CharField(_('first name'), max_length=30)
    username = models.CharField(
        _('username'),
        max_length=150,
        help_text=_(
            '150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator], blank=True, null=True
    )
    email = models.EmailField(_('email address'), unique=True)
    phone = models.CharField(_('Номер телефона'), max_length=16,
                             validators=[RegexValidator(r'^\+\d{9,15}$')])
    place = models.ForeignKey(Territory, verbose_name=_('Населённый пункт'),
                              related_name='users', blank=True, null=True)
    photo = models.ImageField(_('Фото'), upload_to='users',
                              blank=True, null=True)
    shipping_address = models.CharField(_('Адрес доставки'), max_length=255,
                                        blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone', 'first_name']


class Message(models.Model):
    sender = models.ForeignKey(User, verbose_name=_('Отправитель'),
                               related_name='outbox')
    receiver = models.ForeignKey(User, verbose_name=_('Получатель'),
                                 related_name='inbox')
    message = models.TextField(_('Teкст сообщения'))
    created_at = models.DateTimeField(_('Дата отправки'), auto_now_add=True)

    class Meta:
        verbose_name = _('Сообщение')
        verbose_name_plural = _('Сообщения')

    def __unicode__(self):
        return ' -> '.join(map(str, (self.sender, self.receiver)))


@receiver(user_signed_up)
def registered(request, user, sociallogin=None, **kwargs):
    if sociallogin:
        data = sociallogin.account.extra_data
        provider = sociallogin.account.provider

        def load_user_photo(url):
            result = urllib.urlretrieve(url)
            file_name = '{}/{}_{}'.format(provider,data['id'] , os.path.basename(url))
            if provider == 'facebook':
                file_name += '.jpg'
            user.photo.save(file_name, File(open(result[0])))

        if provider == 'twitter':
            url = data['profile_image_url'].replace('normal', '400x400')
            load_user_photo(url)

        if provider == 'facebook':
            user.first_name = data['first_name']
            user.last_name = data['last_name']
            # user.username = 'facebook' + str(data['id'])
            url = "https://graph.facebook.com/{}/picture?type=large".format(data['id'])
            load_user_photo(url)

        if provider == 'google':
            url = data['picture']
            load_user_photo(url)

        user.save()

users/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.forms import Select, TextInput

from users.models import User


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'first_name', 'last_name', 'username', 'place', 'photo', 'shipping_address')
        widgets = {
            'place': Select(attrs={'class': 'phone-cheract bold'}),
            'first_name': TextInput(attrs={'class': 'phone-cheract bold'}),
            'last_name': TextInput(attrs={'class': 'phone-cheract bold'}),
            'email': TextInput(attrs={'class': 'phone-cheract bold'}),
            'phone': TextInput(attrs={'class': 'phone-cheract bold'}),
        }

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseForbidden
from django.views.generic import TemplateView, UpdateView

from users.forms import UserUpdateForm
from users.models import User


class Cabinet(TemplateView):
    template_name = 'users/cabinet.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        return super(Cabinet, self).dispatch(request, *args, **kwargs)


class ProfileUpdateView(UpdateView):
    template_name = 'users/profile_update.html'
    model = User
    # fields = ['username']
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        return super(ProfileUpdateView, self).dispatch(request, *args, **kwargs)


class ProfileRatingView(TemplateView):
    template_name = 'users/profile_rating.html'


class ProfilePurchasesView(TemplateView):
    template_name = 'users/profile_purchases.html'


class ProfileSalesView(TemplateView):
    template_name = 'users/profile_sales.html'


class ProfileSettingsView(TemplateView):
    template_name = 'users/profile_settings.html'

users/templates/users/cabinet.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %} КАБИНЕТ ПОЛЬЗОВАТЕЛЯ {% endblock title %}

{% block content %}
    <div class="content container" id="part1">
        <div class="shadow row m-0 m-t-50">
            {% include 'users/cabinet_sidebar.html' %}
            <div class="personal_cabinet_body">
                {% include 'users/cabinet_header.html' with title='КАБИНЕТ ПОЛЬЗОВАТЕЛЯ' %}
                <div class="row m-0 personal_cabinet_content">
                    <div class="col-xs-8 cabinet_content_main">
                        <div class="f-12">
                            {{ request.user.first_name }}, добро пожаловать в Ваш личный кабинет!
                            <br><br>
                            В личном кабинете собраны инструменты, необходимые для удобной работы в сервисе sellFone: Вы можете редактировать личную информацию, следить за рейтингом и наградами, проверять ход выполнения заказов, просматривать историю сделок, писать отзывы о продавцах, создавать и редактировать объявления о продаже своего устройства.
                        </div>
                        <h5 class="m-t-50"><b>ВАШИ СДЕЛКИ</b></h5>
                        <div class="text-center grey-color">
                            <img class="m-b-15" src="{% static 'images/personal_cab/line.png' %}">
                            <p>У вас нет сделок</p>
                            <p class="f-16"><b>Совершите свою первую сделку</b></p>

                            <div class="m-t-40 m-b-40 row">
                                <div class="col-xs-3 p-10 p-r-10">
                                    <a href="{% url 'products:add' %}" class="btn-action">Продать<br> на sellFone</a>
                                </div>
                                <div class="col-xs-3 p-10 p-r-10">
                                    <a href="#" class="btn-action">Выкуп<br> устройства</a>
                                </div>
                                <div class="col-xs-3 p-10 p-r-10">
                                    <a href="#" class="btn-action">Обмен<br> на новый</a>
                                </div>
                                <div class="col-xs-3 p-10 p-r-10">
                                    <a href="{% url 'products:products' %}" class="btn-action">Купить<br> на sellFone</a>
                                </div>
                            </div>
                        </div>

                        <div>
                            <div role="button" class="collapse_line row" data-toggle="collapse" data-target="#howSell" aria-expanded="false" aria-controls="howSell">
                                <div class="">
                                    КАК ПРОДАТЬ?
                                    <span style="float: right;" class="f-12 m-t-5 bold grey-color glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                                </div>
                            </div>
                            <div class="collapse collapse_line_content" id="howSell" aria-expanded="true" style="">
                                <img class="infograph" style="width: 100%" src="{% static 'images/infograph1.png' %}">
                            </div>
                        </div>
                        <div>
                            <div role="button" class="collapse_line row" data-toggle="collapse" data-target="#howBuy" aria-expanded="false" aria-controls="howBuy">
                                <div class="">
                                    КАК КУПИТЬ?
                                    <span style="float: right;" class="f-12 m-t-5 bold grey-color glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                                </div>
                            </div>
                            <div class="collapse collapse_line_content" id="howBuy" aria-expanded="true" style="">
                                <img class="infograph" style="width: 100%" src="{% static 'images/infograph2.png' %}">
                            </div>
                        </div>
                        <div class="row m-t-40 p-b-65">
                            <div class="col-xs-6 p-r-10">
                                <iframe width="100%" height="175" src="https://www.youtube.com/embed/wJdeVtnUxuk" frameborder="0" allowfullscreen></iframe>
                            </div>
                            <div class="col-xs-6 p-l-10">
                                <iframe width="100%" height="175" src="https://www.youtube.com/embed/wJdeVtnUxuk" frameborder="0" allowfullscreen></iframe>
                            </div>
                        </div>
                    </div>
                    {% include 'users/cabinet_sidebar_right.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block extrajs %}
    <script src="{% static 'js/icheck.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/circle-progress.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('select').niceSelect();

            $("input[type='checkbox']").iCheck({
                checkboxClass: 'icheckbox_minimal',
                radioClass: 'iradio_minimal',
                increaseArea: '10%'
            });

            $('.circle-progress').circleProgress({
                fill: {
                    gradient: ["#2e9df7", "#0f7ed8"]
                }
            }).on('circle-animation-progress', function(event, progress, stepValue) {

                $(this).find('strong').text((stepValue.toFixed(2).substr(2))+'%');
            });

        })
    </script>
{% endblock %}

users/templates/users/cabinet_header.html
{% load staticfiles %}
{% load thumbnail %}
<div class="row m-0 personal_cabinet_header">
    <div class="col-xs-8"><h3 class="f-16">{{ title }}</h3></div>
    <div class="control_panel col-xs-4 justify-between">
        <div class="control_elem">
            <img src="{% static 'images/ico/white/msg.png' %}">
            <div class="control_elem-count">
                <p>2</p>
            </div>
        </div>
        <div class="control_elem">
            <img src="{% static 'images/ico/white/bell.png' %}">
        </div>
        <div class="control_elem">
            <a href="{% url 'profile:settings' %}">
                <img src="{% static 'images/ico/white/settings.png' %}">
            </a>
        </div>
        <div class="control_elem">
            <a href="{% url 'account_logout' %}" class="f-10 exit">Выйти</a>
        </div>
    </div>
</div>

users/templates/users/cabinet_sidebar.html
{% load staticfiles %}
{% load thumbnail %}
<aside class="cabinet_sidebar">
    <div class="sidebar_personal_info">
        <img class="m-b-15" src="{{ request.user.photo|thumbnail_url:'avatar_60' }}">
        <a href="{% url 'profile:cabinet' %}">
            <p class="personal_username">{{ request.user.get_full_name }}</p>
        </a>
        <p class="personal_add-info">{{ request.user.place }}, {{ request.user.date_joined|timesince }} на портале</p>
        <p class="rating f-12" style="float: none;">
            <span class="active glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="active glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="active glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="active glyphicon glyphicon-star" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        </p>
    </div>
    <div class="sidebar_menu">
        <a class="menu-item {% if 'update' in request.path %} active {% endif %} " href="{% url 'profile:update' %}">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/user.png' %}">
            <span style="vertical-align: middle">Личные данные </span>
        </a>
        <a class="menu-item{% if 'rating' in request.path %} active {% endif %}" href="{% url 'profile:rating' %}">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/cup.png' %}">
            <span style="vertical-align: middle">Рейтинг и награды</span>
        </a>
        <a class="menu-item" href="#">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/wallet.png' %}">
            <span style="vertical-align: middle">Доставка и оплата</span>
        </a>
        <a class="menu-item {% if 'sales' in request.path %} active {% endif %}" href="{% url 'profile:sales' %}">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/tag.png' %}">
            <span style="vertical-align: middle">Продажи</span>
        </a>
        <a class="menu-item {% if 'purchases' in request.path %} active {% endif %}" href="{% url 'profile:purchases' %}">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/cart.png' %}">
            <span style="vertical-align: middle">Покупки</span>
        </a>
        <a class="menu-item" href="#">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/stats.png' %}">
            <span style="vertical-align: middle">Мониторинг цен</span>
        </a>
        <a class="menu-item" href="#">
            <img class="menu-item-ico" src="{% static 'images/ico/grey/help.png' %}">
            <span style="vertical-align: middle">Помощь</span>
        </a>
        <a class="menu-item blue" href="{% url 'products:add' %}">
            <span style="vertical-align: middle">Продать устройство</span>
        </a>
    </div>
</aside>

users/templates/users/cabinet_sidebar_right.html
{% load staticfiles %}
{% load thumbnail %}
{% load user_tag %}

<div class="col-xs-4 p-t-35">
    <p><b>ПРОФИЛЬ</b></p>
    <div class="m-b-25 m-t-25">
        <div class="flex">
            <div class="m-r-15">
                <div class="circle-progress" id="circle" data-value="{% user_progress request.user float=True %}" data-size="60" data-thickness="4" data-reverse="true">
                    <strong class="percent"></strong>
                </div>
            </div>
            <div class="inln-blck f-12">
                <p class="bold">Ваш профиль заполнен на {% user_progress request.user %}%</p>
                <p>Совет для улучшения профиля: подтвердите номер телефона</p>
                <br>
                <a class="f-14 bold underline blue-color" href="{% url 'profile:update' %}">УЛУЧШИТЬ!</a>
            </div>
        </div>
    </div>
    <!-- -->
    <div class="row imptnt-blck flex">
        <div class="m-r-15">
            <img src="{% static 'images/rewards/verfied.png' %}">
        </div>
        <div class="f-12">
            <p class="green-color m-b-15 bold">Повысте уровень доверия!</p>
            <p>
                Подтвердите данные
                и получите первую награду
                “Проверенный пользователь”!
            </p>
            <br>
            <a class="f-14 bold underline blue-color" href="{% url 'profile:update' %}">ПОДТВЕРДИТЬ!</a>
        </div>
    </div>
    <!-- -->
    <p class="bold m-t-35 m-b-40">ПОДТВЕРЖДЕНИЕ ДАННЫХ</p>
    <ul class="data_to_verified">
        <li class="msg_b">E-mail <span class="status verify"></span></li>
        <li class="phone_b">Телефон <span class="status unverify"></span></li>
        <li class="social_b">Социальные сети <span class="status verify"></span></li>
        <li class="user_b">Личность <span class="status unverify"></span></li>
        <li class="pay_b">Платежные данные <span class="status verify"></span></li>
    </ul>
</div>

users/templates/users/profile_settings.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %} Продажи {% endblock title %}

{% block content %}
    <div class="content container" id="part1">
        <div class="shadow row m-0 m-t-50">
            {% include 'users/cabinet_sidebar.html' %}
                <div class="personal_cabinet_body">
                {% include 'users/cabinet_header.html' with title='НАСТРОЙКИ ПРОФИЛЯ' %}
                <div class="row m-0 personal_cabinet_content">
                    <div class="col-xs-8 cabinet_content_main">
                        <div class="f-12">
                            В этом разделе Вы можете подтвердить, улучшить или изменить свои личные данные, которые необходимы для совершения сделки.
                        </div>
                        <h5 class="line-h"><nobr>Изменение пароля</nobr><hr></h5>

                        <table class="form-table">
                            <tr class="chose-phone-cheract">
                                <td>
                                    <p class="cheract-label">Текущий пароль</p>
                                </td>
                                <td>
                                    <input type="password" placeholder="*****" class="phone-cheract">
                                </td>
                            </tr>

                            <tr class="chose-phone-cheract">
                                <td>
                                    <p class="cheract-label">Новый пароль</p>
                                </td>
                                <td>
                                    <input type="password" placeholder="*****" class="phone-cheract">
                                </td>
                            </tr>
                            <tr class="chose-phone-cheract">
                                <td>
                                    <p class="cheract-label">Повторите пароль</p>
                                </td>
                                <td>
                                    <input type="password" placeholder="*****" class="phone-cheract">
                                </td>
                            </tr>
                            <tr class="chose-phone-cheract">
                                <td>

                                </td>
                                <td>
                                    <button class="confirm-mail" style="padding: 0px 8px;">Сохранить пароль</button>
                                </td>
                            </tr>
                        </table>
                    </div>
                    {% include 'users/cabinet_sidebar_right.html' %}
                </div>
            </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block extrajs %}
    <script src="{% static 'js/icheck.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/circle-progress.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('[data-toggle="popover"]').hover(
                function () {
                    $(this).popover('show');
                },
                function () {
                    $(this).popover('hide');
                }
            );

            $('select').niceSelect();
            $(".add-photo input[type='file']").simpleFileInput({
                placeholder : '<b>Загрузить копию</b>',
                allowedExts : ['png', 'gif', 'jpg', 'jpeg'],
                wrapperClass : 'addtnl-file-input',
                width: false,
                uploadPlace: '#upload-place',
                uploadImg: true
            });

            $("input[type='checkbox'], input[type='radio']").iCheck({
                checkboxClass: 'iradio_square-blue c-check',
                radioClass: 'iradio_square-blue c-check',
            });

            $('.circle-progress').circleProgress({
                fill: {
                    gradient: ["#2e9df7", "#0f7ed8"]
                }
            }).on('circle-animation-progress', function(event, progress, stepValue) {

                $(this).find('strong').text((stepValue.toFixed(2).substr(2))+'%');
            });
        })
    </script>
    <style>
        .sfi-js .addtnl-file-input .sfi-filename {border: 2px solid #2e9df7;}
        .sfi-js .sfi-wrapper .sfi-filename {color: #2e9df7;}
    </style>
    {% endblock extrajs %}