order/urls.py
from django.conf.urls import url, include
from order import views
# from .views import AddProductView


urlpatterns = [
    url(
        r'^create_order/(?P<product_pk>\d+)/$',
        views.ChoseOrderType,
        name='chose_order_type'
    ),
    url(
        r'^create_order/(?P<product_pk>\d+)/(?P<order_type_pk>\d+)/$',
        views.OrderCreate,
        name='order_create'
    ),
    url(r'^error_pay/$', views.ErrorPay.as_view(), name='error_pay'),
    url(r'^done_pay/$', views.DonePay.as_view(), name='done_pay'),
]

products/urls.py
from django.conf.urls import url, include
from products import views
# from .views import AddProductView
from products.views import SearchProductView, chart_period

urlpatterns = [
    url(r'^search/$', SearchProductView.as_view(), name='product_search'),
    url(
        r'^$',
        views.ProductListView.as_view(),
        name='products'
    ),
    url(
        r'^product_detail/(?P<pk>\d+)/$',
        views.ProductDetailView.as_view(),
        name='product_detail'
    ),
    url(
        r'add/$',
        views.add_product,
        name='add',
    ),
    url(
        r'get_parameters/$',
        views.get_parameters,
        name='get_parameters',
    ),
    url(r'period-chart/(?P<period>\d+)/(?P<pk>\d+)/$', chart_period, name='chart_period')
]

sellfone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles import views

from products.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^$', index, name='index'),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^price_wizard/', include('price_wizard.urls', namespace='price_wizard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

templates/base.html
{% load staticfiles %}
{% load socialaccount %}
{% load sekizai_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {{ config.SITE_NAME }} {% endblock %}</title>
    <meta charset="utf-8">
    {% block stylesheets %}
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/owl.carousel.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/owl.theme.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/owl.transitions.css" %}">

        <link rel="stylesheet" type="text/css" href="{% static 'css/grey.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/chosen.min.css' %}">

        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    {% endblock %}
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
<header>
	<nav class="navbar navbar-default nmb">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class='hidden-xs hidden-sm'>
                        <div class="socials row" style="margin-right: 0;">
                            <a href="#"><span class='symbol' id="twtr-ico">twitterbird</span></a>
                            <a href="#"><span class="symbol" id="fb-ico">facebook</span></a>
                            <a href="#"><span class="symbol" id="ggl-ico">googleplus</span></a>
                            <a href="#"><span class="symbol" id="ytb-ico">youtube</span></a>
                        </div>
                    </li>
                    <li style="font-size: 12px;"><a href="{% url 'index' %}">Главная</a></li>
                    <li style="font-size: 12px;"><a href="{% url 'products:products' %}">Купить</a></li>
		            <li style="font-size: 12px;"><a href="{% url 'products:add' %}">Продать</a></li>
		            <li style="font-size: 12px;"><a href="#">О сервисе</a></li>
		            <li style="font-size: 12px;"><a href="#">Контакты</a></li>
                    <li class="dropdown">
                        <a  class="green-color dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b> +380 97 123 45 67</b><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="">+380 97 123 45 67</a></li>
		            	    <li><a href="#">+380 97 123 45 67</a></li>
		            	    <li><a href="#">+380 97 123 45 67</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown blue">
                        <a href="{% url 'products:add' %}" class="dropdown-toggle" >Продать устройство</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right hidden-sm">
                    <li>
                        <p class='languages'>
				            <a class="active language" href="#">RU</a>
				            <a class="language" href="#">UA</a>
				            <a class="language" href="#">EN</a>
                        </p>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

	<!--BEGIN HEADE_BOTTOM-->
	<div class="bottom-header">
		<div class="container">
			<div class="col-sm-2 col-xs-12 logo"><img src="{% static 'images/logo.png' %}"></div>
			<div class="col-xs-5 middle">
				<form class="search" type="get" action="{% url 'products:product_search' %}">
					<select class="search-select">
						<option>Киев</option>
						<option>Харьков</option>
						<option>Львов</option>
						<option>Донецк</option>
					</select>
					<div class="search-form">
                        <input placeholder="Поиск" class="search-inp" type="text" name="q">
                        <button type="submit" class="search-btn"><img src="{% static 'images/search-ico.png' %}"></button>
					</div>
				</form>
			</div>
			<div class="col-xs-3 hidden-xs support">

				<div class=" col-xs-6 control_elem">
					<div class="control_elem-img">
						<img src="{% static 'images/basket-ico.png' %}">
						<div class="control_elem-count"><p>2</p></div>
					</div>
					<span class="control_elem-text">Корзина</span>
				</div>
				<div class="col-xs-6 control_elem favorite">
					<div class="control_elem-img">
						<img src="{% static 'images/favorite-ico.png' %}">
						<div class="control_elem-count"><p>2</p></div>
					</div>
					<span class="control_elem-text">Избранное</span>
				</div>

			</div>
			{% if request.user.is_anonymous %}
                        {% include 'includes/login_window.html' %}
                    {% else %}
                        {% include 'includes/profile_bar.html' %}
                    {% endif %}
		</div>
	</div>
	<!--END HEADE_BOTTOM-->


    <div class="content" style="background-color: #f6f6f6;">
{% block content %}
{% endblock %}
    </div>
	<div style="background-color: #494949;">
        <div class="content container" id="bottom">
            <div class="col-xs-6 col-sm-5 col-md-3 logo"><img src="{% static "images/logo-white.png" %}"></div>
            <div class="col-xs-7 col-md-6 hidden-xs">
                <div class="col-xs-4">
                    <ul>
                        КУПИТЬ
                        <li>IPhones</li>
                        <li>Смартфоны</li>
                        <li>Планшеты</li>
                    </ul>
                </div>
                <div class="col-xs-4">
                    <ul>
                        ПРОДАТЬ
                        <li>IPhones</li>
                        <li>Смартфоны</li>
                        <li>Планшеты</li>
                    </ul>
                </div>
                <div class="col-xs-4">
                    <ul>
                        О СЕРВИСЕ
                        <li>Команда</li>
                        <li>Оплата</li>
                        <li>Гарантия</li>
                        <li>Доставка</li>
                        <li>Пользовательское соглашение</li>
                        <li>Политика</li>
                        <li>Конфиденциальность</li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3 hidden-xs">
                <p id="email">info@sellfone.com</p>
            </div>
        </div>
        <div class="mobile-menu" style="display: none;">
            <ul>
                <li><a href="#"><b>ГЛАВНАЯ</b></a></li>
                <li><a href="#"><b>КУПИТЬ</b></a></li>
                <li><a href="#"><b>ПРОДАТЬ</b></a></li>
                <li><a href="#"><b>О СЕРВИСЕ</b></a></li>
                <li><a href="#"><b>КОНТАКТЫ</b></a></li>
            </ul>
            <div class="search m-t-30">
                <div id="mobile-close">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </div>
                <form class="search-form">
                    <input class="search-inp" placeholder="Поиск" type="text" name="">
                    <button class="btn search-btn"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                </form>
            </div>
        </div>
    </div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/icheck.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/chosen.jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/lightslider.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".account").on("click", function(){
                var $p = $(this).parent();
                if($p.hasClass('active')){
                    $p.removeClass('active');
                }
                else{
                    $p.addClass('active');
                }
            });

            $(".next-window-disp").on("click", function(e){
                e.preventDefault();
                $(".window-disp").removeClass("active");
                var $p = $($(this).attr("href"));
                $p.addClass("active");
            });

            $('[data-toggle="popover"]').hover(
                function () {
                    $(this).popover('show');
                },
                function () {
                    $(this).popover('hide');
                }
            );
            $('select').niceSelect();
        })
    </script>
{% block extrajs %}
{% endblock %}
{% render_block 'extrajs' %}

</body>
</html>